"""squish.squash.integrations.huggingface — HuggingFace Hub adapter for Squash.

After a model is pushed to the Hub, this adapter runs attestation locally and
uploads the resulting SBOM + policy reports as additional files in the model
repository.  It also writes a ``squash-compliance.md`` model-card section so
that the attestation status is human-readable on the Hub UI.

Usage::

    from squish.squash.integrations.huggingface import HFSquash

    HFSquash.attest_and_push(
        repo_id="myorg/llama-3.1-8b-int4",
        model_path=Path("./llama-3.1-8b-int4"),
        policies=["eu-ai-act", "nist-ai-rmf"],
        hf_token="hf_...",
    )

The function pushes these files to the repo root:
  - ``squash/cyclonedx-mlbom.json``
  - ``squash/spdx-mlbom.json``
  - ``squash/squash-attest.json``
  - ``squash/squash-policy-<name>.json``  (one per policy)
  - ``squash/squash-compliance.md``       (human-readable summary)
"""

from __future__ import annotations

import logging
from pathlib import Path

from squish.squash.attest import AttestConfig, AttestPipeline, AttestResult

log = logging.getLogger(__name__)

_COMPLIANCE_MD_TEMPLATE = """\
## Squash Compliance Attestation

| Key | Value |
|-----|-------|
| Status | **{status}** |
| Security scan | `{scan}` |
{policy_rows}

*Generated by [Squish Squash](https://github.com/wesleyscholl/squish). \
This section is auto-updated on every model push.*
"""


class HFSquash:
    """Push Squash attestation artifacts to a HuggingFace Hub repository."""

    @staticmethod
    def attest_and_push(
        repo_id: str,
        model_path: Path,
        *,
        hf_token: str = "",
        policies: list[str] | None = None,
        sign: bool = False,
        fail_on_violation: bool = False,
        repo_prefix: str = "squash",
        **attest_kwargs,
    ) -> AttestResult:
        """Attest *model_path* and upload artifacts to Hub repo *repo_id*.

        Parameters
        ----------
        repo_id:
            HuggingFace Hub repository ID, e.g. ``"myorg/llama-3-8b"``.
        model_path:
            Local model directory.
        hf_token:
            HuggingFace API token.  Falls back to ``HF_TOKEN`` env var if empty.
        policies:
            Policy templates to evaluate.
        sign:
            Sign via Sigstore.
        fail_on_violation:
            Raise on compliance failure.
        repo_prefix:
            Directory prefix inside the Hub repo, defaults to ``"squash"``.
        """
        try:
            from huggingface_hub import HfApi
        except ImportError as e:
            raise ImportError(
                "huggingface_hub is required. Install with: pip install huggingface-hub"
            ) from e

        out = model_path.parent / "squash"
        config = AttestConfig(
            model_path=model_path,
            output_dir=out,
            hf_repo=repo_id,
            policies=policies if policies is not None else ["enterprise-strict"],
            sign=sign,
            fail_on_violation=fail_on_violation,
            **attest_kwargs,
        )
        result = AttestPipeline.run(config)

        # Build human-readable compliance section
        policy_rows = "\n".join(
            f"| Policy: {name} | {'✅ PASS' if pr.passed else '❌ FAIL'} |"
            for name, pr in result.policy_results.items()
        )
        compliance_md = _COMPLIANCE_MD_TEMPLATE.format(
            status="PASS ✅" if result.passed else "FAIL ❌",
            scan=(result.scan_result.status if result.scan_result else "skipped"),
            policy_rows=policy_rows,
        )
        compliance_path = out / "squash-compliance.md"
        compliance_path.write_text(compliance_md)

        # Upload to Hub
        api = HfApi(token=hf_token or None)
        for p in out.iterdir():
            if p.is_file():
                api.upload_file(
                    path_or_fileobj=str(p),
                    path_in_repo=f"{repo_prefix}/{p.name}",
                    repo_id=repo_id,
                    repo_type="model",
                    commit_message=f"squash: attestation artifacts [{p.name}]",
                )
                log.info("Pushed %s → %s/%s/%s", p.name, repo_id, repo_prefix, p.name)

        return result
